-- liquibase formatted sql

-- changeset k.abylay:1
ALTER TABLE IF EXISTS ITEMS
    ADD COLUMN COUNTRY_ID BIGINT,
    ADD FOREIGN KEY (COUNTRY_ID)
        REFERENCES COUNTRIES (ID);

-- changeset k.abylay:2
INSERT INTO ITEMS(NAME, DESCRIPTION, PRICE, COUNTRY_ID)
VALUES ('IPHONE 15 PRO MAX', '256 GB', 700000, (SELECT ID FROM COUNTRIES WHERE CODE = 'KAZ'));